package ProjectEuler;

import java.math.BigInteger;

/*
 Author: Siya Agrawal
 Date: 02/08/22
 Email: siya02.agrawal@gmail.com
 Published on: 2022,July,Tuesday
 Description: The sequence of triangle numbers is generated by adding the natural numbers. 
 So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

                    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

                            1: 1
                            3: 1,3
                            6: 1,2,3,6
                            10: 1,2,5,10
                            15: 1,3,5,15
                            21: 1,3,7,21
                            28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 */
public class Question12 {
    public static int divisors (int n) {
        int counter = 0;
        for (int i = 1; i*i <= n; i++) {
            //checking the divisibility
            if (n % i == 0) counter+=2;
        }
        return counter;
    }
    public static void main(String[] args) {
        //variable declaration
        int i = 1, x = 2;
        boolean found = false;
        while (!found) {
            //checking the number of divisors
            if (divisors(i) > 500) {
                System.out.println(i);
                found = true;
            }
            else {
                //incrementing the value for next iteration
                i+=x;
                x++;
            }
        }
    }
}
